# Custom Language File for Launcher Customizer

[ejs.app]
title = "Laru Studios Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "https://x.com/larusmp?s=21d"
mediaInstagramURL = "https://www.tiktok.com/@larusmp?_t=8l3iP5Dd770&_r=1"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/TbSgutHwcT"

[ejs.settings]
sourceGithubLink = "https://github.com/Shisuiicaro/Laru-studios-launcher"
supportLink = "https://github.com/Shisuiicaro/Laru-studios-launcher/issues"
selectLanguage = "Select a Language"
changeLanguageTitle = "Change the launcher language"
changeLanguageDesc = "You can change the language in the list below. This text will not change if you change the language so you can find your wayback here to change it back"

[ejs.welcome]
welcomeHeader = "WELCOME TO LARU"
welcomeDescription = """
Bem-vindo ao LaruSMP, onde sua aventura no Minecraft começa! Um servidor que vai te dar experiências inesquecíveis no melhor servidor SMP que você pode imaginar. Junte-se à nossa comunidade e faça muitos amigos, sempre estaremos aqui para te acolher!

Mas espera, tem mais! Fique de olho no servidor do discord para todas as atualizações e não ficar por fora. Caso queira, temos formulários sempre abertos para STAFF, modeladores, editores, etc, se sinta a vontade!

Então, o que você está esperando? Clique em "Continuar" e seja bem vindo a ilha Laru!
"""

[ejs.overlay]
changedLanguageHeader = "You changed the previous language"